### ISSUE TITLE
[Reflection] ParamSpec, member_ref

### ISSUE THREAD

**Issue by sa-tasche** [onrirr/c3-web#76]
# Reflection _membersof_

There should be a separate page for all reflection property structures;\
if they are identical to [member_ref](https://c3-lang.org/generic-programming/reflection/#membersof), this should be mentioned.

## Tasks

- [ ] [ParamSpec](https://c3-lang.org/generic-programming/reflection/#paramsof)
- [ ] Like _member_ref_ (they may be identical).
   - [ ] [associated](https://c3-lang.org/generic-programming/reflection/#associated)
   - [ ] [parentof](https://c3-lang.org/generic-programming/reflection/#parentof)
   - [ ] [values](https://c3-lang.org/generic-programming/reflection/#values)
   - [ ] [returns](https://c3-lang.org/generic-programming/reflection/#returns)

**Comment by ManuLinares** [comment]
Are them already covered by these?

https://c3-lang.org/generic-programming/reflection/#members
https://c3-lang.org/generic-programming/reflection/#params
https://c3-lang.org/generic-programming/reflection/#parent
https://c3-lang.org/generic-programming/reflection/#values
https://c3-lang.org/generic-programming/reflection/#returns

Could we close this?
